{{- /*
Copyright Bouygues Telecom SA
SPDX-License-Identifier: APACHE-2.0
*/}}
{{- if and .Values.secrets (ne .Values.secrets.type "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "spin.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secrets.type }}
{{- end }}
