{{- /*
Copyright Bouygues Telecom SA
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spin.serviceAccountName" . }}
  labels:
    {{- include "spin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- printf "- name: %s-dockercfg-xxxxx" (include "spin.fullname" .) | nindent 4 }}
  {{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 4 }}
{{- end }}
